### ISSUE TITLE
RJ45 or RJ11 output?

### ISSUE THREAD

**Issue by norn93** [openenergymonitor/emonVoltageSense#5]
Version 1.2 and 1.3 of emonVoltageSense both use an RJ45 for their output, but the EmonTx4 still uses an RJ11 for it's input. There's no obvious reason for the difference, as far as I can tell, unless it's because RJ45 cables more commonly have 6 conductors, rather than the default 4 of the RJ11. I don't know enough about that. Is the plan to upgrade the EmonTx4 to use an RJ45 as the input of the EmonTx4 (as well as the output of the EmonTx4, which might confuse some people), or to stick with the RJ11, in which case should the emonVoltageSense revert to using the RJ11?

@glynhudson, I notice that you just approved the pull request for version 1.3 of emonVoltageSense as authored by @TiagoPaulaSilva, and you authored version 1.1
@TrystanLea, I notice that you initially created version 1.2.

**Comment by glynhudson** [comment]
The reason to move to RJ45 is to enable more current to be carried to power the [emonpi2](https://github.com/openenergymonitor/emonpi2). RJ45 has more conductors, we common conductors together to enable more current to be carried.

**Comment by norn93** [comment]
OK, that makes sense. But, why is the current version of the EmonTx4 not compatible with the current version of the emonVoltageSense? Is the emonpi2 the new preferred current monitor?

**Comment by glynhudson** [comment]
The Rj45 version and emonPi2 have not yet been manufactured, testing and development is ongoing. The emonPi2 is the same as the emonTx V4 in terms of functionality but avoids the requirement for a separate emonBase.
