### ISSUE TITLE
Why does the emonTx V3 have 2 - 22 Ohm resistors in parallel

### ISSUE THREAD

**Issue by NicoPowers** [openenergymonitor/emonVoltageSense#8]
Hello,

I was wondering why the emonTx V3 has 2 - 22 Ohm parallel resistors instead of the 1 22 Ohm resistor as calculated in the documentation?

Having 2 - 22 Ohm resistors in parallel is effectively make the burden resistor 11 Ohms instead of 22 Ohms; is this a mistake?

Thank you

**Comment by glynhudson** [comment]
Only one resistor is populated, the two parts on the schematic are to give the option for both SMT and THU hole footprints 

![emonVs_1phase-jpg-1280×698-](https://github.com/openenergymonitor/emonVoltageSense/assets/758844/6898fcdf-c8dc-4f55-826e-37926023118d)
